/*
 * generated by Xtext 2.9.1
 */
package org.casualintellect.parser.antlr;

import com.google.inject.Inject;
import org.casualintellect.parser.antlr.internal.InternalCasualIntellectParser;
import org.casualintellect.services.CasualIntellectGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CasualIntellectParser extends AbstractAntlrParser {

	@Inject
	private CasualIntellectGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCasualIntellectParser createParser(XtextTokenStream stream) {
		return new InternalCasualIntellectParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CasualIntellectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CasualIntellectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
