/*
 * generated by Xtext 2.9.1
 */
package org.casualintellect.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CasualIntellectAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/casualintellect/parser/antlr/internal/InternalCasualIntellect.tokens");
	}
}
