/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect;

import org.casualintellect.CasualIntellectStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CasualIntellectStandaloneSetup extends CasualIntellectStandaloneSetupGenerated {
  public static void doSetup() {
    CasualIntellectStandaloneSetup _casualIntellectStandaloneSetup = new CasualIntellectStandaloneSetup();
    _casualIntellectStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
