/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect;

import org.casualintellect.AbstractCasualIntellectRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CasualIntellectRuntimeModule extends AbstractCasualIntellectRuntimeModule {
}
