/*
 * generated by Xtext 2.9.1
 */
package org.casualintellect.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCasualIntellectScopeProvider extends DelegatingScopeProvider {
}
