/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.casualIntellect;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.casualintellect.casualIntellect.CasualIntellectFactory
 * @model kind="package"
 * @generated
 */
public interface CasualIntellectPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "casualIntellect";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.casualintellect.org/CasualIntellect";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "casualIntellect";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CasualIntellectPackage eINSTANCE = org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl.init();

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.ModelImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>List of states</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__LIST_OF_STATES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.StateImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getState()
   * @generated
   */
  int STATE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Before</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__BEFORE = 1;

  /**
   * The feature id for the '<em><b>After</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__AFTER = 2;

  /**
   * The feature id for the '<em><b>In Process</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__IN_PROCESS = 3;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__TRANSITIONS = 4;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.TransitionsImpl <em>Transitions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.TransitionsImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getTransitions()
   * @generated
   */
  int TRANSITIONS = 2;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITIONS__LIST = 0;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITIONS__TRANSITIONS = 1;

  /**
   * The number of structural features of the '<em>Transitions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.TransitionImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__CONDITION = 1;

  /**
   * The feature id for the '<em><b>Methods</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__METHODS = 2;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.ProcessInStateImpl <em>Process In State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.ProcessInStateImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getProcessInState()
   * @generated
   */
  int PROCESS_IN_STATE = 4;

  /**
   * The feature id for the '<em><b>Methods</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_IN_STATE__METHODS = 0;

  /**
   * The number of structural features of the '<em>Process In State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_IN_STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.ProcessAfterStateImpl <em>Process After State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.ProcessAfterStateImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getProcessAfterState()
   * @generated
   */
  int PROCESS_AFTER_STATE = 5;

  /**
   * The feature id for the '<em><b>Methods</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_AFTER_STATE__METHODS = 0;

  /**
   * The number of structural features of the '<em>Process After State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_AFTER_STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.ProcessBeforeStateImpl <em>Process Before State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.ProcessBeforeStateImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getProcessBeforeState()
   * @generated
   */
  int PROCESS_BEFORE_STATE = 6;

  /**
   * The feature id for the '<em><b>Methods</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_BEFORE_STATE__METHODS = 0;

  /**
   * The number of structural features of the '<em>Process Before State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_BEFORE_STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.ExpressionImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 7;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.OrImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getOr()
   * @generated
   */
  int OR = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.AndImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getAnd()
   * @generated
   */
  int AND = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.NotImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getNot()
   * @generated
   */
  int NOT = 10;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__EXPRESSION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.StringConstantImpl <em>String Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.StringConstantImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getStringConstant()
   * @generated
   */
  int STRING_CONSTANT = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.casualintellect.casualIntellect.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.casualintellect.casualIntellect.impl.BoolConstantImpl
   * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getBoolConstant()
   * @generated
   */
  int BOOL_CONSTANT = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.casualintellect.casualIntellect.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.casualintellect.casualIntellect.Model#getList_of_states <em>List of states</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List of states</em>'.
   * @see org.casualintellect.casualIntellect.Model#getList_of_states()
   * @see #getModel()
   * @generated
   */
  EReference getModel_List_of_states();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see org.casualintellect.casualIntellect.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link org.casualintellect.casualIntellect.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.casualintellect.casualIntellect.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.State#getBefore <em>Before</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Before</em>'.
   * @see org.casualintellect.casualIntellect.State#getBefore()
   * @see #getState()
   * @generated
   */
  EReference getState_Before();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.State#getAfter <em>After</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>After</em>'.
   * @see org.casualintellect.casualIntellect.State#getAfter()
   * @see #getState()
   * @generated
   */
  EReference getState_After();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.State#getInProcess <em>In Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>In Process</em>'.
   * @see org.casualintellect.casualIntellect.State#getInProcess()
   * @see #getState()
   * @generated
   */
  EReference getState_InProcess();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.State#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transitions</em>'.
   * @see org.casualintellect.casualIntellect.State#getTransitions()
   * @see #getState()
   * @generated
   */
  EReference getState_Transitions();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.Transitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transitions</em>'.
   * @see org.casualintellect.casualIntellect.Transitions
   * @generated
   */
  EClass getTransitions();

  /**
   * Returns the meta object for the containment reference list '{@link org.casualintellect.casualIntellect.Transitions#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List</em>'.
   * @see org.casualintellect.casualIntellect.Transitions#getList()
   * @see #getTransitions()
   * @generated
   */
  EReference getTransitions_List();

  /**
   * Returns the meta object for the containment reference list '{@link org.casualintellect.casualIntellect.Transitions#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see org.casualintellect.casualIntellect.Transitions#getTransitions()
   * @see #getTransitions()
   * @generated
   */
  EReference getTransitions_Transitions();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see org.casualintellect.casualIntellect.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the attribute '{@link org.casualintellect.casualIntellect.Transition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.casualintellect.casualIntellect.Transition#getName()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.Transition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.casualintellect.casualIntellect.Transition#getCondition()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Condition();

  /**
   * Returns the meta object for the attribute list '{@link org.casualintellect.casualIntellect.Transition#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Methods</em>'.
   * @see org.casualintellect.casualIntellect.Transition#getMethods()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Methods();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.ProcessInState <em>Process In State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process In State</em>'.
   * @see org.casualintellect.casualIntellect.ProcessInState
   * @generated
   */
  EClass getProcessInState();

  /**
   * Returns the meta object for the attribute list '{@link org.casualintellect.casualIntellect.ProcessInState#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Methods</em>'.
   * @see org.casualintellect.casualIntellect.ProcessInState#getMethods()
   * @see #getProcessInState()
   * @generated
   */
  EAttribute getProcessInState_Methods();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.ProcessAfterState <em>Process After State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process After State</em>'.
   * @see org.casualintellect.casualIntellect.ProcessAfterState
   * @generated
   */
  EClass getProcessAfterState();

  /**
   * Returns the meta object for the attribute list '{@link org.casualintellect.casualIntellect.ProcessAfterState#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Methods</em>'.
   * @see org.casualintellect.casualIntellect.ProcessAfterState#getMethods()
   * @see #getProcessAfterState()
   * @generated
   */
  EAttribute getProcessAfterState_Methods();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.ProcessBeforeState <em>Process Before State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process Before State</em>'.
   * @see org.casualintellect.casualIntellect.ProcessBeforeState
   * @generated
   */
  EClass getProcessBeforeState();

  /**
   * Returns the meta object for the attribute list '{@link org.casualintellect.casualIntellect.ProcessBeforeState#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Methods</em>'.
   * @see org.casualintellect.casualIntellect.ProcessBeforeState#getMethods()
   * @see #getProcessBeforeState()
   * @generated
   */
  EAttribute getProcessBeforeState_Methods();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.casualintellect.casualIntellect.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see org.casualintellect.casualIntellect.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.casualintellect.casualIntellect.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.casualintellect.casualIntellect.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see org.casualintellect.casualIntellect.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.casualintellect.casualIntellect.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.casualintellect.casualIntellect.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see org.casualintellect.casualIntellect.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link org.casualintellect.casualIntellect.Not#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.casualintellect.casualIntellect.Not#getExpression()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Expression();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.StringConstant <em>String Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Constant</em>'.
   * @see org.casualintellect.casualIntellect.StringConstant
   * @generated
   */
  EClass getStringConstant();

  /**
   * Returns the meta object for the attribute '{@link org.casualintellect.casualIntellect.StringConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.casualintellect.casualIntellect.StringConstant#getValue()
   * @see #getStringConstant()
   * @generated
   */
  EAttribute getStringConstant_Value();

  /**
   * Returns the meta object for class '{@link org.casualintellect.casualIntellect.BoolConstant <em>Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Constant</em>'.
   * @see org.casualintellect.casualIntellect.BoolConstant
   * @generated
   */
  EClass getBoolConstant();

  /**
   * Returns the meta object for the attribute '{@link org.casualintellect.casualIntellect.BoolConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.casualintellect.casualIntellect.BoolConstant#getValue()
   * @see #getBoolConstant()
   * @generated
   */
  EAttribute getBoolConstant_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CasualIntellectFactory getCasualIntellectFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.ModelImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>List of states</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__LIST_OF_STATES = eINSTANCE.getModel_List_of_states();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.StateImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Before</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__BEFORE = eINSTANCE.getState_Before();

    /**
     * The meta object literal for the '<em><b>After</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__AFTER = eINSTANCE.getState_After();

    /**
     * The meta object literal for the '<em><b>In Process</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__IN_PROCESS = eINSTANCE.getState_InProcess();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__TRANSITIONS = eINSTANCE.getState_Transitions();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.TransitionsImpl <em>Transitions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.TransitionsImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getTransitions()
     * @generated
     */
    EClass TRANSITIONS = eINSTANCE.getTransitions();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITIONS__LIST = eINSTANCE.getTransitions_List();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITIONS__TRANSITIONS = eINSTANCE.getTransitions_Transitions();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.TransitionImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__NAME = eINSTANCE.getTransition_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__CONDITION = eINSTANCE.getTransition_Condition();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__METHODS = eINSTANCE.getTransition_Methods();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.ProcessInStateImpl <em>Process In State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.ProcessInStateImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getProcessInState()
     * @generated
     */
    EClass PROCESS_IN_STATE = eINSTANCE.getProcessInState();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS_IN_STATE__METHODS = eINSTANCE.getProcessInState_Methods();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.ProcessAfterStateImpl <em>Process After State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.ProcessAfterStateImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getProcessAfterState()
     * @generated
     */
    EClass PROCESS_AFTER_STATE = eINSTANCE.getProcessAfterState();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS_AFTER_STATE__METHODS = eINSTANCE.getProcessAfterState_Methods();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.ProcessBeforeStateImpl <em>Process Before State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.ProcessBeforeStateImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getProcessBeforeState()
     * @generated
     */
    EClass PROCESS_BEFORE_STATE = eINSTANCE.getProcessBeforeState();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS_BEFORE_STATE__METHODS = eINSTANCE.getProcessBeforeState_Methods();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.ExpressionImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.OrImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.AndImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.NotImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__EXPRESSION = eINSTANCE.getNot_Expression();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.StringConstantImpl <em>String Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.StringConstantImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getStringConstant()
     * @generated
     */
    EClass STRING_CONSTANT = eINSTANCE.getStringConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_CONSTANT__VALUE = eINSTANCE.getStringConstant_Value();

    /**
     * The meta object literal for the '{@link org.casualintellect.casualIntellect.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.casualintellect.casualIntellect.impl.BoolConstantImpl
     * @see org.casualintellect.casualIntellect.impl.CasualIntellectPackageImpl#getBoolConstant()
     * @generated
     */
    EClass BOOL_CONSTANT = eINSTANCE.getBoolConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_CONSTANT__VALUE = eINSTANCE.getBoolConstant_Value();

  }

} //CasualIntellectPackage
