/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.casualIntellect;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.casualintellect.casualIntellect.Model#getList_of_states <em>List of states</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>List of states</b></em>' containment reference list.
   * The list contents are of type {@link org.casualintellect.casualIntellect.State}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List of states</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List of states</em>' containment reference list.
   * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getModel_List_of_states()
   * @model containment="true"
   * @generated
   */
  EList<State> getList_of_states();

} // Model
