/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.casualIntellect;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process After State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.casualintellect.casualIntellect.ProcessAfterState#getMethods <em>Methods</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getProcessAfterState()
 * @model
 * @generated
 */
public interface ProcessAfterState extends EObject
{
  /**
   * Returns the value of the '<em><b>Methods</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Methods</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methods</em>' attribute list.
   * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getProcessAfterState_Methods()
   * @model unique="false"
   * @generated
   */
  EList<String> getMethods();

} // ProcessAfterState
