/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.casualIntellect;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.casualintellect.casualIntellect.State#getName <em>Name</em>}</li>
 *   <li>{@link org.casualintellect.casualIntellect.State#getBefore <em>Before</em>}</li>
 *   <li>{@link org.casualintellect.casualIntellect.State#getAfter <em>After</em>}</li>
 *   <li>{@link org.casualintellect.casualIntellect.State#getInProcess <em>In Process</em>}</li>
 *   <li>{@link org.casualintellect.casualIntellect.State#getTransitions <em>Transitions</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getState()
 * @model
 * @generated
 */
public interface State extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getState_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.casualintellect.casualIntellect.State#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Before</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Before</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Before</em>' containment reference.
   * @see #setBefore(ProcessBeforeState)
   * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getState_Before()
   * @model containment="true"
   * @generated
   */
  ProcessBeforeState getBefore();

  /**
   * Sets the value of the '{@link org.casualintellect.casualIntellect.State#getBefore <em>Before</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Before</em>' containment reference.
   * @see #getBefore()
   * @generated
   */
  void setBefore(ProcessBeforeState value);

  /**
   * Returns the value of the '<em><b>After</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>After</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>After</em>' containment reference.
   * @see #setAfter(ProcessAfterState)
   * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getState_After()
   * @model containment="true"
   * @generated
   */
  ProcessAfterState getAfter();

  /**
   * Sets the value of the '{@link org.casualintellect.casualIntellect.State#getAfter <em>After</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>After</em>' containment reference.
   * @see #getAfter()
   * @generated
   */
  void setAfter(ProcessAfterState value);

  /**
   * Returns the value of the '<em><b>In Process</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In Process</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In Process</em>' containment reference.
   * @see #setInProcess(ProcessInState)
   * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getState_InProcess()
   * @model containment="true"
   * @generated
   */
  ProcessInState getInProcess();

  /**
   * Sets the value of the '{@link org.casualintellect.casualIntellect.State#getInProcess <em>In Process</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In Process</em>' containment reference.
   * @see #getInProcess()
   * @generated
   */
  void setInProcess(ProcessInState value);

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transitions</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference.
   * @see #setTransitions(Transitions)
   * @see org.casualintellect.casualIntellect.CasualIntellectPackage#getState_Transitions()
   * @model containment="true"
   * @generated
   */
  Transitions getTransitions();

  /**
   * Sets the value of the '{@link org.casualintellect.casualIntellect.State#getTransitions <em>Transitions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transitions</em>' containment reference.
   * @see #getTransitions()
   * @generated
   */
  void setTransitions(Transitions value);

} // State
