/*
 * generated by Xtext 2.9.1
 */
package org.casualintellect


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CasualIntellectStandaloneSetup extends CasualIntellectStandaloneSetupGenerated {

	def static void doSetup() {
		new CasualIntellectStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
